// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/metadata.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MinioKey      string                 `protobuf:"bytes,3,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoRequest) Reset() {
	*x = VideoRequest{}
	mi := &file_proto_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoRequest) ProtoMessage() {}

func (x *VideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoRequest.ProtoReflect.Descriptor instead.
func (*VideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *VideoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *VideoRequest) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *VideoRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateStatusRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type VideoIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoId       string                 `protobuf:"bytes,1,opt,name=video_id,json=videoId,proto3" json:"video_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoIdRequest) Reset() {
	*x = VideoIdRequest{}
	mi := &file_proto_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoIdRequest) ProtoMessage() {}

func (x *VideoIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoIdRequest.ProtoReflect.Descriptor instead.
func (*VideoIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *VideoIdRequest) GetVideoId() string {
	if x != nil {
		return x.VideoId
	}
	return ""
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{3}
}

type VideoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	MinioKey      string                 `protobuf:"bytes,4,opt,name=minio_key,json=minioKey,proto3" json:"minio_key,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoResponse) Reset() {
	*x = VideoResponse{}
	mi := &file_proto_metadata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoResponse) ProtoMessage() {}

func (x *VideoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoResponse.ProtoReflect.Descriptor instead.
func (*VideoResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{4}
}

func (x *VideoResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VideoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VideoResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *VideoResponse) GetMinioKey() string {
	if x != nil {
		return x.MinioKey
	}
	return ""
}

func (x *VideoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *VideoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Videos        []*VideoResponse       `protobuf:"bytes,1,rep,name=videos,proto3" json:"videos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_metadata_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_metadata_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_metadata_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetVideos() []*VideoResponse {
	if x != nil {
		return x.Videos
	}
	return nil
}

var File_proto_metadata_proto protoreflect.FileDescriptor

const file_proto_metadata_proto_rawDesc = "" +
	"\n" +
	"\x14proto/metadata.proto\x12\bmetadata\"t\n" +
	"\fVideoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tminio_key\x18\x03 \x01(\tR\bminioKey\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"H\n" +
	"\x13UpdateStatusRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"+\n" +
	"\x0eVideoIdRequest\x12\x19\n" +
	"\bvideo_id\x18\x01 \x01(\tR\avideoId\"\r\n" +
	"\vListRequest\"\xa4\x01\n" +
	"\rVideoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1b\n" +
	"\tminio_key\x18\x04 \x01(\tR\bminioKey\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"?\n" +
	"\fListResponse\x12/\n" +
	"\x06videos\x18\x01 \x03(\v2\x17.metadata.VideoResponseR\x06videos2\x9a\x02\n" +
	"\x0fMetadataService\x12>\n" +
	"\vCreateVideo\x12\x16.metadata.VideoRequest\x1a\x17.metadata.VideoResponse\x12K\n" +
	"\x11UpdateVideoStatus\x12\x1d.metadata.UpdateStatusRequest\x1a\x17.metadata.VideoResponse\x12=\n" +
	"\bGetVideo\x12\x18.metadata.VideoIdRequest\x1a\x17.metadata.VideoResponse\x12;\n" +
	"\n" +
	"ListVideos\x12\x15.metadata.ListRequest\x1a\x16.metadata.ListResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_metadata_proto_rawDescOnce sync.Once
	file_proto_metadata_proto_rawDescData []byte
)

func file_proto_metadata_proto_rawDescGZIP() []byte {
	file_proto_metadata_proto_rawDescOnce.Do(func() {
		file_proto_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)))
	})
	return file_proto_metadata_proto_rawDescData
}

var file_proto_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_metadata_proto_goTypes = []any{
	(*VideoRequest)(nil),        // 0: metadata.VideoRequest
	(*UpdateStatusRequest)(nil), // 1: metadata.UpdateStatusRequest
	(*VideoIdRequest)(nil),      // 2: metadata.VideoIdRequest
	(*ListRequest)(nil),         // 3: metadata.ListRequest
	(*VideoResponse)(nil),       // 4: metadata.VideoResponse
	(*ListResponse)(nil),        // 5: metadata.ListResponse
}
var file_proto_metadata_proto_depIdxs = []int32{
	4, // 0: metadata.ListResponse.videos:type_name -> metadata.VideoResponse
	0, // 1: metadata.MetadataService.CreateVideo:input_type -> metadata.VideoRequest
	1, // 2: metadata.MetadataService.UpdateVideoStatus:input_type -> metadata.UpdateStatusRequest
	2, // 3: metadata.MetadataService.GetVideo:input_type -> metadata.VideoIdRequest
	3, // 4: metadata.MetadataService.ListVideos:input_type -> metadata.ListRequest
	4, // 5: metadata.MetadataService.CreateVideo:output_type -> metadata.VideoResponse
	4, // 6: metadata.MetadataService.UpdateVideoStatus:output_type -> metadata.VideoResponse
	4, // 7: metadata.MetadataService.GetVideo:output_type -> metadata.VideoResponse
	5, // 8: metadata.MetadataService.ListVideos:output_type -> metadata.ListResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_metadata_proto_init() }
func file_proto_metadata_proto_init() {
	if File_proto_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_metadata_proto_rawDesc), len(file_proto_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_metadata_proto_goTypes,
		DependencyIndexes: file_proto_metadata_proto_depIdxs,
		MessageInfos:      file_proto_metadata_proto_msgTypes,
	}.Build()
	File_proto_metadata_proto = out.File
	file_proto_metadata_proto_goTypes = nil
	file_proto_metadata_proto_depIdxs = nil
}
